version: '3.8'

services:
  camcheck:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SERVER_PORT=80
      - CAMCHECK_CAMERA_FORCE_FALLBACK=true
      - CAMCHECK_SECURITY_USERNAME=admin
      - CAMCHECK_SECURITY_PASSWORD=changeme
    volumes:
      - recordings:/app/recordings
    restart: unless-stopped

volumes:
  recordings:
    driver: local 