version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/camcheck
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - FRONTEND_PATH=/app/frontend/web
    volumes:
      - ./data:/data
      - ./frontend/web:/app/frontend/web
    networks:
      - camcheck-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/web:/usr/share/nginx/html
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - camcheck-network

networks:
  camcheck-network:
    driver: bridge 