services:
  - type: web
    name: camcheck
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    healthCheckPath: /api/v1/system/status
    autoDeploy: false
    numInstances: 1
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 10000
      - key: JAVA_OPTS
        value: "-Xmx38m -Xms20m -XX:MaxMetaspaceSize=64m -XX:CompressedClassSpaceSize=16m -XX:ReservedCodeCacheSize=16m -XX:+UseSerialGC -XX:+UseStringDeduplication -XX:+DisableExplicitGC -XX:SoftRefLRUPolicyMSPerMB=0 -XX:MaxDirectMemorySize=5M -Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom -XX:+UseCompressedOops -XX:+UseCompressedClassPointers -XX:ThreadStackSize=256k"
      # VM capacity measurement settings
      - key: vm_capacity_measure
        value: "true"
      - key: vm_capacity_stress_test
        value: "false"
      # Dynamic memory optimization settings
      - key: dynamic_memory_enabled
        value: "true"
      - key: dynamic_memory_target_percent
        value: "70"
      - key: dynamic_memory_check_interval
        value: "3000"
      # Memory optimization settings
      - key: memory_target_mb
        value: "30"
      - key: memory_max_mb
        value: "38"
      - key: memory_aggressive_gc
        value: "true"
      - key: memory_check_interval_ms
        value: "5000"
      # Low resource mode
      - key: LOW_RESOURCE_MODE
        value: "true"
      # Undertow settings
      - key: UNDERTOW_WORKER_THREADS
        value: "2"
      - key: UNDERTOW_IO_THREADS
        value: "1"
      - key: UNDERTOW_BUFFER_SIZE
        value: "4096"
      - key: UNDERTOW_DIRECT_BUFFERS
        value: "false"
      - key: UNDERTOW_MAX_CONNECTIONS
        value: "50"
      - key: UNDERTOW_IDLE_TIMEOUT
        value: "30000"
      - key: UNDERTOW_ENABLE_HTTP2
        value: "false"
      # Request throttling
      - key: camcheck_throttle_enabled
        value: "true"
      - key: camcheck_throttle_max_concurrent_requests
        value: "2"
      - key: camcheck_throttle_timeout_ms
        value: "3000"
      - key: camcheck_throttle_cpu_threshold
        value: "0.8"
      # JVM optimization settings
      - key: AGGRESSIVE_GC
        value: "true"
      - key: GC_INTERVAL_MS
        value: "120000"
      - key: MEMORY_HIGH_THRESHOLD
        value: "70"
      - key: MEMORY_CRITICAL_THRESHOLD
        value: "85"
      - key: MEMORY_RECOVERY_THRESHOLD
        value: "60"
      # Media settings
      - key: MEDIA_POOL_MAX_SIZE
        value: "5"
      - key: MEDIA_CACHE_MAX_SIZE
        value: "10"
      - key: THROTTLE_MAX_CONCURRENT_REQUESTS
        value: "2"
      # Memory-efficient frame processor settings
      - key: frame_processor_cache_size
        value: "5"
      - key: frame_processor_cache_expire_ms
        value: "5000"
      - key: frame_processor_max_concurrent
        value: "2"
      # Image processing settings
      - key: image_denoise_default_method
        value: "fast-bilateral"
      - key: image_denoise_strength
        value: "0.5"
      - key: image_denoise_optimize_performance
        value: "true"
    disk:
      name: recordings
      mountPath: /app/recordings
      sizeGB: 1
    sleepMode: when-idle
    healthCheckTimeout: 5
    gracefulShutdownTimeoutSeconds: 30 