# CamCheck Application Configuration

# Server settings
server:
  port: 8080
  servlet:
    context-path: /
  ssl:
    enabled: false # Set to true for production with proper certificates

# Spring settings
spring:
  application:
    name: cam-check
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Custom CamCheck settings
camcheck:
  # Security settings
  security:
    username: admin
    password: 123
    # List of trusted IPs that can access the system without authentication
    # Default is localhost (IPv4 and IPv6)
    trusted-ips: 127.0.0.1,::1,192.168.1.0/24,10.0.0.0/8
    
  # Camera settings
  camera:
    # Options: webcam (USB camera) or ip (IP camera)
    type: webcam
    
    # Frame rate (frames per second)
    frame-rate: 30
    
    # Resolution
    width: 640
    height: 480
    
    # Camera device index (usually 0 for the first camera)
    device-index: 0
    
    # Force fallback mode (use this if you don't have a camera or want to test without one)
    force-fallback: false
    
    # IP camera settings (if type is set to 'ip')
    ip-url: http://192.168.1.100:8080/video
    
  # Motion detection settings
  motion-detection:
    enabled: false # Disabled per user request
    sensitivity: 30 # 1-100, higher is more sensitive
    cooldown-period: 10 # Minimum time between detections (seconds)
    
  # Storage settings
  storage:
    # Save recordings when motion is detected
    record-on-motion: false # Disabled since motion detection is disabled
    
    # Recording length in seconds
    recording-length: 30
    
    # Maximum storage space for recordings (MB)
    max-size-mb: 5000
    
    # Delete oldest recordings when storage limit is reached
    delete-oldest: true
    
    # Path for recordings (relative to application)
    recordings-path: ./recordings

# Swagger/OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
  show-actuator: false
  
# Logging configuration
logging:
  level:
    root: INFO
    com.camcheck: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO 