# CamCheck Application Configuration - Development Profile

# Server settings
server:
  port: ${SERVER_PORT:8080}
  address: ${SERVER_ADDRESS:0.0.0.0}
  servlet:
    context-path: /
  ssl:
    enabled: false
  undertow:
    worker-threads: ${UNDERTOW_WORKER_THREADS:16}
    buffer-size: ${UNDERTOW_BUFFER_SIZE:8192}
    direct-buffers: ${UNDERTOW_DIRECT_BUFFERS:true}
    max-http-post-size: ${UNDERTOW_MAX_HTTP_POST_SIZE:10485760}
    io-threads: ${UNDERTOW_IO_THREADS:4}
    accesslog:
      enabled: ${UNDERTOW_ACCESSLOG_ENABLED:false}
      pattern: ${UNDERTOW_ACCESSLOG_PATTERN:'%t %a "%r" %s (%D ms)'}
    options:
      server:
        ALWAYS_SET_DATE: ${UNDERTOW_ALWAYS_SET_DATE:true}
        MAX_ENTITY_SIZE: ${UNDERTOW_MAX_ENTITY_SIZE:10485760}
      socket:
        TCP_NODELAY: ${UNDERTOW_TCP_NODELAY:true}
        REUSE_ADDRESSES: ${UNDERTOW_REUSE_ADDRESSES:true}

# Spring settings
spring:
  application:
    name: cam-check
  thymeleaf:
    cache: ${THYMELEAF_CACHE:false}
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}

# Custom CamCheck settings
camcheck:
  # API versioning settings
  api:
    latest-version: "v2"
    supported-versions: ["v1", "v2"]
    deprecation-warning: true
  
  # JWT settings for mobile authentication
  jwt:
    # Secret key for JWT signature (should be environment variable in production)
    secret-key: ${JWT_SECRET_KEY:6u9h4HzKqBXbpnhLXktYoVm7sR2jDfGc}
    # JWT expiration time in milliseconds (1 hour by default)
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}
    # Refresh token expiration in milliseconds (7 days by default)
    refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000}
    # Issuer name in JWT claims
    issuer: ${JWT_ISSUER:camcheck}
    # Token prefix in Authorization header
    token-prefix: "Bearer "
    # Header name for Authorization
    header: "Authorization"
    
  # Mobile app settings
  mobile:
    # Android package name for push notifications
    android-package-name: ${MOBILE_ANDROID_PACKAGE:com.camcheck.app}
    # iOS bundle ID for push notifications
    ios-bundle-id: ${MOBILE_IOS_BUNDLE:com.camcheck.app}
    # Default quality level for new mobile installations (low, medium, high)
    default-quality: ${MOBILE_DEFAULT_QUALITY:medium}
    # Max concurrent sessions per mobile device
    max-sessions: ${MOBILE_MAX_SESSIONS:1}
    # Enable background mode for continuous camera access
    background-mode-enabled: ${MOBILE_BACKGROUND_MODE:false}
    # Push notification settings
    push-notifications:
      # Enable push notifications
      enabled: ${MOBILE_PUSH_ENABLED:true}
      # Firebase project ID for push notifications
      firebase-project-id: ${MOBILE_FIREBASE_PROJECT_ID:camcheck-mobile}
      # Firebase credentials file path (JSON)
      firebase-credentials-file: ${MOBILE_FIREBASE_CREDENTIALS:}
      # Maximum daily notification limit per user
      daily-limit: ${MOBILE_PUSH_DAILY_LIMIT:50}
      # Quiet hours settings
      quiet-hours:
        enabled: ${MOBILE_QUIET_HOURS_ENABLED:false}
        start: ${MOBILE_QUIET_HOURS_START:22:00}
        end: ${MOBILE_QUIET_HOURS_END:07:00}
        timezone: ${MOBILE_QUIET_HOURS_TIMEZONE:UTC}

  # Security settings
  security:
    # User accounts
    users:
      - username: ${SECURITY_USERNAME_LUXUBOO:dev_user}
        password: ${SECURITY_PASSWORD_LUXUBOO:dev_password}
        role: USER
      - username: ${SECURITY_USERNAME_KAITRAN:dev_admin}
        password: ${SECURITY_PASSWORD_KAITRAN:dev_admin_password}
        role: ADMIN
    # Legacy credentials (kept for backward compatibility)
    username: ${LEGACY_USERNAME:legacy_user}
    password: ${LEGACY_PASSWORD:legacy_password}
    # List of trusted IPs that can access the system without authentication
    trusted-ips: ${SECURITY_TRUSTED_IPS:127.0.0.1,::1}
    # Superuser credentials
    superuser:
      username: ${SUPERUSER_USERNAME:superuser}
      password: ${SUPERUSER_PASSWORD:superuser_password}
  
  # Analytics settings
  analytics:
    # Enable analytics collection
    enabled: ${ANALYTICS_ENABLED:true}
    
    # Metrics retention period in days
    metrics-retention-days: ${ANALYTICS_METRICS_RETENTION_DAYS:30}
    
    # Alert thresholds
    alert-threshold-cpu: ${ANALYTICS_ALERT_THRESHOLD_CPU:80}
    alert-threshold-memory: ${ANALYTICS_ALERT_THRESHOLD_MEMORY:80}
    alert-threshold-disk: ${ANALYTICS_ALERT_THRESHOLD_DISK:90}
    
    # Dashboard settings
    dashboard:
      # Enable dashboard
      enabled: ${ANALYTICS_DASHBOARD_ENABLED:true}
      
      # Dashboard refresh interval in seconds
      refresh-interval: ${ANALYTICS_DASHBOARD_REFRESH_INTERVAL:60}
      
      # Default time range for charts in minutes
      default-time-range: ${ANALYTICS_DASHBOARD_DEFAULT_TIME_RANGE:60}
      
      # Maximum number of data points per chart
      max-data-points: ${ANALYTICS_DASHBOARD_MAX_DATA_POINTS:100}
    
    # Notification settings
    notifications:
      # Enable email notifications
      email-enabled: ${ANALYTICS_NOTIFICATIONS_EMAIL_ENABLED:false}
      
      # Email recipients (comma-separated)
      email-recipients: ${ANALYTICS_NOTIFICATIONS_EMAIL_RECIPIENTS:}
      
      # Enable webhook notifications
      webhook-enabled: ${ANALYTICS_NOTIFICATIONS_WEBHOOK_ENABLED:false}
      
      # Webhook URL
      webhook-url: ${ANALYTICS_NOTIFICATIONS_WEBHOOK_URL:}
      
      # Minimum alert level for notifications (INFO, WARNING, ERROR, CRITICAL)
      min-alert-level: ${ANALYTICS_NOTIFICATIONS_MIN_ALERT_LEVEL:WARNING}
  
  # Encryption settings
  encryption:
    # Enable end-to-end encryption
    enabled: ${ENCRYPTION_ENABLED:true}
    
    # AES key size (128, 192, 256)
    key-size: ${ENCRYPTION_KEY_SIZE:256}
    
    # Elliptic curve for key exchange (secp256r1, secp384r1, secp521r1)
    ec-curve: ${ENCRYPTION_EC_CURVE:secp256r1}
    
    # GCM authentication tag length in bits (128, 120, 112, 104, 96)
    gcm-tag-length: ${ENCRYPTION_GCM_TAG_LENGTH:128}
    
    # Key rotation settings
    key-rotation:
      # Enable automatic key rotation
      enabled: ${ENCRYPTION_KEY_ROTATION_ENABLED:true}
      
      # Key rotation interval in hours
      interval-hours: ${ENCRYPTION_KEY_ROTATION_INTERVAL:24}
      
      # Maximum key age in hours
      max-age-hours: ${ENCRYPTION_KEY_MAX_AGE:48}
    
    # Session key settings
    session:
      # Session key timeout in minutes
      timeout-minutes: ${ENCRYPTION_SESSION_TIMEOUT:60}
      
      # Require re-authentication after timeout
      require-reauth: ${ENCRYPTION_SESSION_REQUIRE_REAUTH:true}
    
  # Camera settings
  camera:
    # Options: webcam (USB camera) or ip (IP camera)
    type: ${CAMERA_TYPE:webcam}
    
    # Frame rate (frames per second)
    frame-rate: ${CAMERA_FRAME_RATE:15}
    
    # Resolution
    width: ${CAMERA_WIDTH:640}
    height: ${CAMERA_HEIGHT:480}
    
    # Camera device index (usually 0 for the first camera)
    device-index: ${CAMERA_DEVICE_INDEX:0}
    
    # Force fallback mode (use this if you don't have a camera or want to test without one)
    force-fallback: ${CAMERA_FORCE_FALLBACK:true}
    
    # IP camera settings (if type is set to 'ip')
    ip-url: ${CAMERA_IP_URL:http://localhost:8081/video}
    
  # Motion detection settings
  motion-detection:
    enabled: ${MOTION_DETECTION_ENABLED:false}
    sensitivity: ${MOTION_DETECTION_SENSITIVITY:20}
    cooldown-period: ${MOTION_DETECTION_COOLDOWN:5000}
    
  # Storage settings
  storage:
    # Save recordings when motion is detected
    record-on-motion: ${STORAGE_RECORD_ON_MOTION:false}
    
    # Recording length in seconds
    recording-length: ${STORAGE_RECORDING_LENGTH:10}
    
    # Maximum storage space for recordings (MB)
    max-size-mb: ${STORAGE_MAX_SIZE_MB:1000}
    
    # Delete oldest recordings when storage limit is reached
    delete-oldest: ${STORAGE_DELETE_OLDEST:true}
    
    # Path for recordings (relative to application)
    recordings-path: ${STORAGE_RECORDINGS_PATH:./recordings}
    
  # Media handling settings
  media:
    # Compression quality (0.0-1.0, where 1.0 is highest quality)
    compression-quality: ${MEDIA_COMPRESSION_QUALITY:0.85}
    
    # Minimum allowed compression quality
    min-compression-quality: ${MEDIA_MIN_COMPRESSION_QUALITY:0.5}
    
    # Maximum allowed compression quality
    max-compression-quality: ${MEDIA_MAX_COMPRESSION_QUALITY:0.95}
    
    # Default image format
    default-format: ${MEDIA_DEFAULT_FORMAT:jpeg}
    
    # Maximum audio data size in bytes
    max-audio-size: ${MEDIA_MAX_AUDIO_SIZE:100000}
    
    # Codec settings
    codec:
      # Preferred codec (h264, vp8, vp9, av1, webp, jpeg)
      preferred: ${MEDIA_CODEC_PREFERRED:h264}
      
      # Fallback codec when preferred is not available
      fallback: ${MEDIA_CODEC_FALLBACK:jpeg}
      
      # Default codec quality (0.0-1.0)
      quality: ${MEDIA_CODEC_QUALITY:0.85}
      
      # Enable hardware acceleration when available
      hardware-acceleration: ${MEDIA_CODEC_HARDWARE_ACCELERATION:true}
      
      # Maximum bitrate for video (bits per second)
      max-bitrate: ${MEDIA_CODEC_MAX_BITRATE:1500000}
      
      # Target bitrate for video (bits per second)
      target-bitrate: ${MEDIA_CODEC_TARGET_BITRATE:800000}
      
      # Keyframe interval (frames)
      keyframe-interval: ${MEDIA_CODEC_KEYFRAME_INTERVAL:30}
    
    # Resolution scaling settings
    resolution-scaling:
      # Enable dynamic resolution scaling
      enabled: ${MEDIA_RESOLUTION_SCALING_ENABLED:true}
      
      # Minimum allowed width
      min-width: ${MEDIA_RESOLUTION_SCALING_MIN_WIDTH:160}
      
      # Minimum allowed height
      min-height: ${MEDIA_RESOLUTION_SCALING_MIN_HEIGHT:120}
      
      # Maximum allowed width
      max-width: ${MEDIA_RESOLUTION_SCALING_MAX_WIDTH:1280}
      
      # Maximum allowed height
      max-height: ${MEDIA_RESOLUTION_SCALING_MAX_HEIGHT:720}
      
      # Default scale factor (0.0-1.0)
      default-scale: ${MEDIA_RESOLUTION_SCALING_DEFAULT_SCALE:0.8}
      
      # Network latency thresholds (milliseconds)
      latency-threshold-high: ${MEDIA_RESOLUTION_SCALING_LATENCY_HIGH:300}
      latency-threshold-medium: ${MEDIA_RESOLUTION_SCALING_LATENCY_MEDIUM:150}
      latency-threshold-low: ${MEDIA_RESOLUTION_SCALING_LATENCY_LOW:50}
    
    # Delta encoding settings
    delta-encoding:
      # Enable delta encoding
      enabled: ${MEDIA_DELTA_ENCODING_ENABLED:true}
      
      # Pixel change threshold (0-255)
      threshold: ${MEDIA_DELTA_ENCODING_THRESHOLD:10}
      
      # Block size in pixels
      block-size: ${MEDIA_DELTA_ENCODING_BLOCK_SIZE:16}
      
      # Keyframe interval (frames)
      keyframe-interval: ${MEDIA_DELTA_ENCODING_KEYFRAME_INTERVAL:30}
    
    # Mobile optimization settings
    mobile:
      # Enable mobile-specific optimizations
      enabled: ${MEDIA_MOBILE_ENABLED:true}
      
      # Detect mobile devices automatically
      auto-detect: ${MEDIA_MOBILE_AUTO_DETECT:true}
      
      # Maximum resolution for mobile devices
      max-width: ${MEDIA_MOBILE_MAX_WIDTH:480}
      max-height: ${MEDIA_MOBILE_MAX_HEIGHT:360}
      
      # Frame rate limit for mobile devices (fps)
      max-frame-rate: ${MEDIA_MOBILE_MAX_FRAME_RATE:15}
      
      # Compression quality for mobile devices (0.0-1.0)
      compression-quality: ${MEDIA_MOBILE_COMPRESSION_QUALITY:0.7}
      
      # Power saving mode (reduces CPU/GPU usage)
      power-saving: ${MEDIA_MOBILE_POWER_SAVING:false}
      
      # Battery threshold for power saving mode (percent)
      battery-threshold: ${MEDIA_MOBILE_BATTERY_THRESHOLD:20}
      
      # Network type optimization (auto, wifi, cellular)
      network-optimization: ${MEDIA_MOBILE_NETWORK_OPTIMIZATION:auto}
      
      # Cellular data usage settings
      cellular:
        # Allow streaming over cellular
        allow-streaming: ${MEDIA_MOBILE_CELLULAR_ALLOW_STREAMING:true}
        
        # Maximum bitrate over cellular (bits per second)
        max-bitrate: ${MEDIA_MOBILE_CELLULAR_MAX_BITRATE:500000}
        
        # Enable data saving mode over cellular
        data-saving: ${MEDIA_MOBILE_CELLULAR_DATA_SAVING:true}
    
    # Audio settings
    audio:
      # Enable audio support
      enabled: ${MEDIA_AUDIO_ENABLED:true}
      
      # Audio sample rate
      sample-rate: ${MEDIA_AUDIO_SAMPLE_RATE:44100}
      
      # Audio bit depth
      bit-depth: ${MEDIA_AUDIO_BIT_DEPTH:16}
      
      # Audio channels (1=mono, 2=stereo)
      channels: ${MEDIA_AUDIO_CHANNELS:1}
    
    # WebSocket settings for media streaming
    websocket:
      # Maximum message size for WebSocket (bytes)
      max-message-size: ${MEDIA_WEBSOCKET_MAX_MESSAGE_SIZE:1048576}
      
      # Buffer size for WebSocket (bytes)
      buffer-size: ${MEDIA_WEBSOCKET_BUFFER_SIZE:1048576}
      
      # Send timeout for WebSocket (milliseconds)
      send-timeout: ${MEDIA_WEBSOCKET_SEND_TIMEOUT:10000}
      
      # Heartbeat interval (milliseconds)
      heartbeat-interval: ${MEDIA_WEBSOCKET_HEARTBEAT_INTERVAL:5000}
  
  # WebRTC settings
  webrtc:
    # Enable WebRTC support
    enabled: ${WEBRTC_ENABLED:true}
    
    # STUN servers for ICE negotiation (comma-separated list)
    stun-servers: ${WEBRTC_STUN_SERVERS:stun:stun.l.google.com:19302,stun:stun1.l.google.com:19302}
    
    # TURN servers for ICE negotiation (comma-separated list)
    turn-servers: ${WEBRTC_TURN_SERVERS:}
    
    # TURN server authentication
    turn-username: ${WEBRTC_TURN_USERNAME:}
    turn-credential: ${WEBRTC_TURN_CREDENTIAL:}
    
    # ICE transport policy (all, relay)
    ice-transport-policy: ${WEBRTC_ICE_TRANSPORT_POLICY:all}
    
    # Bundle policy (max-bundle, balanced, max-compat)
    bundle-policy: ${WEBRTC_BUNDLE_POLICY:balanced}
    
    # Signaling timeout (milliseconds)
    signaling-timeout: ${WEBRTC_SIGNALING_TIMEOUT:30000}
    
    # Connection timeout (milliseconds)
    connection-timeout: ${WEBRTC_CONNECTION_TIMEOUT:60000}
    
    # Media constraints
    media:
      # Video constraints
      video:
        # Enable video
        enabled: ${WEBRTC_VIDEO_ENABLED:true}
        
        # Minimum frame rate
        min-frame-rate: ${WEBRTC_VIDEO_MIN_FRAME_RATE:15}
        
        # Maximum frame rate
        max-frame-rate: ${WEBRTC_VIDEO_MAX_FRAME_RATE:30}
        
        # Minimum width
        min-width: ${WEBRTC_VIDEO_MIN_WIDTH:320}
        
        # Maximum width
        max-width: ${WEBRTC_VIDEO_MAX_WIDTH:1280}
        
        # Minimum height
        min-height: ${WEBRTC_VIDEO_MIN_HEIGHT:240}
        
        # Maximum height
        max-height: ${WEBRTC_VIDEO_MAX_HEIGHT:720}
        
        # Facing mode (user, environment)
        facing-mode: ${WEBRTC_VIDEO_FACING_MODE:user}
      
      # Audio constraints
      audio:
        # Enable audio
        enabled: ${WEBRTC_AUDIO_ENABLED:true}
        
        # Enable echo cancellation
        echo-cancellation: ${WEBRTC_AUDIO_ECHO_CANCELLATION:true}
        
        # Enable noise suppression
        noise-suppression: ${WEBRTC_AUDIO_NOISE_SUPPRESSION:true}
        
        # Enable auto gain control
        auto-gain-control: ${WEBRTC_AUDIO_AUTO_GAIN_CONTROL:true}
    
    # Data channel settings
    data-channel:
      # Enable data channels
      enabled: ${WEBRTC_DATA_CHANNEL_ENABLED:true}
      
      # Maximum message size (bytes)
      max-message-size: ${WEBRTC_DATA_CHANNEL_MAX_MESSAGE_SIZE:16384}
      
      # Ordered delivery
      ordered: ${WEBRTC_DATA_CHANNEL_ORDERED:true}
      
      # Maximum retransmit time (milliseconds)
      max-retransmit-time: ${WEBRTC_DATA_CHANNEL_MAX_RETRANSMIT_TIME:1000}

# Swagger/OpenAPI configuration
springdoc:
  api-docs:
    path: ${SPRINGDOC_API_DOCS_PATH:/api-docs}
  swagger-ui:
    path: ${SPRINGDOC_SWAGGER_UI_PATH:/swagger-ui}
    operationsSorter: ${SPRINGDOC_OPERATIONS_SORTER:alpha}
    tagsSorter: ${SPRINGDOC_TAGS_SORTER:alpha}
    disable-swagger-default-url: ${SPRINGDOC_DISABLE_DEFAULT_URL:true}
  show-actuator: ${SPRINGDOC_SHOW_ACTUATOR:true}
  
# Logging configuration - console only, no file logging
logging:
  pattern:
    console: ${LOGGING_PATTERN_CONSOLE:%d{HH:mm:ss} %-5p [%c{1}] %m%n}
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.camcheck: ${LOGGING_LEVEL_CAMCHECK:INFO}
    org.springframework.web: ${LOGGING_LEVEL_SPRING_WEB:INFO}
    org.springframework.security: ${LOGGING_LEVEL_SPRING_SECURITY:INFO}
    org.springframework.messaging: ${LOGGING_LEVEL_SPRING_MESSAGING:INFO}
    org.springframework.web.socket: ${LOGGING_LEVEL_SPRING_WEBSOCKET:INFO}
    io.undertow: ${LOGGING_LEVEL_UNDERTOW:INFO} 
